version: "3.8"
services:
  backend-api:
    build: ./backend
    restart: on-failure
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/app/src
      - ./backend/index.jx:/app/index.jx
    depends_on:
      - database
    
  frontend:
    build: ./frontend
    container_name: frontend
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend-api

  database:
    image: mongo:6.0
    container_name: database
    restart: on-failure
    ports:
      - 27017:27017
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mexpress
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@database:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    depends_on:
      - database
    